name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    name: Build and Deploy Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        env:
          VITE_API_PROXY_BASE: https://aireceptionist-func.azurewebsites.net/api
          VITE_FUNCTION_HOST: https://aireceptionist-func.azurewebsites.net
        with:
          azure_static_web_apps_api_token: ${{ secrets.AIRECEPTIONIST_STATIC_WEB }}
          action: upload
          app_location: "./AIReceptionNewUI"
          api_location: ""
          output_location: "dist"
          app_build_command: "npm install && npm run build"
